#! /bin/sh
. "${HOME}/.config/bspwm/config"
notify-send -u low "Bspwm rice loaded" &

bspc config border_width        2
bspc config window_gap          8

# wal
wal -a 75 -i "${HOME}/Pictures/bg"
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

killall compton ; compton &
