#! /bin/sh
bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio             0.49
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true
bspc config honor_size_hints        true

killall compton
xrdb "${HOME}/.Xresources"
if ! `command -v hsetroot 2>/dev/null`; then
    xsetroot
fi

# Default colors
bspc config normal_border_color     "#30302f"
bspc config active_border_color     "#474645"
bspc config focused_border_color    "#817f7f"
bspc config presel_feedback_color   "#f4d775"
