#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Pick your poison
#. "${HOME}/.config/bspwm/bspwmrcRiced"
. "${HOME}/.config/bspwm/bspwmrcNormal"

bspc rule -a Firefox desktop='^1'
bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura  state=tiled
bspc rule -a Virtualbox state=floating
bspc rule -a Qemu-system-x86_64 state=floating

# Useless capslock key begone
setxkbmap -layout "$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $2}')" -option ctrl:nocaps

xscreensaver &
redshift -l 48.853:2.35 &
