#! /bin/sh
bspc config border_width        1
bspc config window_gap          2

# Default colors
bspc config normal_border_color     "#30302f"
bspc config active_border_color     "#474645"
bspc config focused_border_color    "#817f7f"
bspc config presel_feedback_color   "#f4d775"

# Black background
if ! `command -v hsetroot 2>/dev/null`; then
    xsetroot
fi
killall compton

wal --theme ${WAL_THEME:-"monokai"}
