#! /bin/sh
# shared config stuff

# Behavior settings
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true
bspc config honor_size_hints        true

# App settings
bspc rule -a Firefox desktop='^1'
bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura  state=tiled
bspc rule -a Virtualbox state=floating
bspc rule -a Qemu-system-x86_64 state=floating
